name: drivers
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=3.9.0 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    # ðŸ”¥ Ø§Ù„Ø­Ø²Ù… Ø§Ù„Ø£Ø³Ø§Ø³ÙŠØ©
    url_launcher: ^6.1.11
    http: ^1.1.0
    flutter_localizations:
        sdk: flutter
    google_maps_flutter: ^2.5.0
    uuid: ^4.2.1
    connectivity_plus: ^6.1.5
    intl: ^0.20.2
    flutter_map: ^8.2.2
    geolocator: ^14.0.2
    image_picker: ^1.0.4
    shared_preferences: ^2.2.2
    provider: ^6.1.1

    # ðŸ”¥ Ø­Ø²Ù… Firebase
    firebase_core: ^4.1.1
    firebase_auth: ^6.1.0
    cloud_firestore: ^6.0.2
    firebase_messaging: ^16.0.2
    flutter_local_notifications: ^19.5.0
    syncfusion_flutter_charts: ^31.1.23
    latlong2: ^0.9.1 # Ù„Ø­Ø³Ø§Ø¨ Ø§Ù„Ø¥Ø­Ø¯Ø§Ø«ÙŠØ§Øª

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    generate: true