  name: drivers
  description: A new Flutter project.
  publish_to: 'none'

  version: 1.0.0+1

  environment:
    sdk: '>=3.5.0 <4.0.0'

  dependencies:
    flutter:
      sdk: flutter
    flutter_localizations:
      sdk: flutter

    # Ø§Ù„Ø­Ø²Ù… Ø§Ù„Ø£Ø³Ø§Ø³ÙŠØ©
    google_maps_flutter: ^2.5.0
    uuid: ^4.2.1
    connectivity_plus: ^7.0.0
    intl: ^0.20.2  # â¬…ï¸ Ø­Ø¯Ø¯ Ø¥ØµØ¯Ø§Ø± Ù…ØªÙˆØ§ÙÙ‚
    flutter_map: ^8.2.2
    geolocator: ^14.0.2
    image_picker: ^1.0.4
    shared_preferences: ^2.2.2
    provider: ^6.1.1
    google_translator: ^1.0.0
    http: ^1.1.0

    # Ø­Ø²Ù… Firebase
    firebase_core: ^4.1.1
    firebase_auth: ^6.1.0
    cloud_firestore: ^6.0.2
    firebase_messaging: ^16.0.2
    flutter_local_notifications: ^19.5.0
    syncfusion_flutter_charts: ^31.1.23
    # ðŸ”¥ Ø§Ù„Ø­Ø²Ù… Ø§Ù„Ù†Ø§Ù‚ØµØ© Ù„Ù„Ù…Ù†ØµØ§Øª (Ø§Ù„Ø­Ù„ Ø§Ù„Ù†Ù‡Ø§Ø¦ÙŠ)
    #shared_preferences_linux: ^2.1.1
    #shared_preferences_windows: ^2.1.1
    #shared_preferences_web: ^2.1.1  # â¬…ï¸ Ø£Ø¶Ù Ù‡Ø°Ø§ Ø£ÙŠØ¶Ø§Ù‹

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^2.0.0

  flutter:
    uses-material-design: true
    generate: true

  dependency_overrides:
      intl: ^0.20.2